name: Pack ESC-RANK LoRA (English only, fast)

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  pack_lora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # 安装带 hf_transfer 的 HF CLI
      - name: Install huggingface client (with hf_transfer)
        run: |
          python -m pip install -U "huggingface_hub[hf_transfer]" hf_transfer

      # 仅下载 7 个 *_en 目录；启用并行加速
      - name: Download LoRA dirs via hf CLI (include patterns)
        env:
          HF_HUB_ENABLE_HF_TRANSFER: "1"
        run: |
          set -e
          mkdir -p ESC-RANK
          # 重试三次以防瞬时网络抖动
          for i in 1 2 3; do
            hf download haidequanbu/ESC-RANK \
              --repo-type model \
              --local-dir ESC-RANK \
              --local-dir-use-symlinks False \
              --include "overall_en/**" \
              --include "empathic_en/**" \
              --include "fluency_en/**" \
              --include "tech_en/**" \
              --include "diversity_en/**" \
              --include "suggestion_en/**" \
              --include "human_en/**" && break || sleep 10
          done

      - name: Pack & checksum
        run: |
          tar -czf ESC-RANK_en_lora.tgz -C ESC-RANK .
          sha256sum ESC-RANK_en_lora.tgz > ESC-RANK_en_lora.tgz.sha256

      - name: Create release and upload
        uses: softprops/action-gh-release@v2
        with:
          tag_name: esc-rank-lora-${{ github.run_id }}
          generate_release_notes: true
          files: |
            ESC-RANK_en_lora.tgz
            ESC-RANK_en_lora.tgz.sha256
